[book]
authors = ["Miabread"]
language = "en"
multilingual = false
src = "src"
title = "Sonance Docs"

[output.html]
additional-js = ["theme/custom-highlight.js"]
git-repository-url = "https://github.com/Miabread/sonance"
